#!/bin/bash

set -e
sudo apt update
sudo systemctl enable docker
sudo systemctl start docker
docker --version > docker_version.txt
docker info | head -n 20 >> docker_version.txt

sudo systemctl status docker --no-pager | head -n 15
docker ps -a >> docker_status.txt


docker pull nginx:alpine
docker images | grep nginx
docker tag nginx:alpine my-nginx:v1.0
docker images | grep -E 'nginx|my-nginx'
docker inspect nginx:alpine | grep -A 5 "Architecture"
docker rmi my-nginx:v1.0 >> image_oprations.txt



